// src/features/dashboard/DashboardPage.vue
<script setup lang="ts">
import { workRecords, type WorkRecord } from "./dashboard-model";

function riskType(record: WorkRecord): "success" | "warning" | "danger" {
  return record.risk === "High" ? "danger" : record.risk === "Medium" ? "warning" : "success";
}
</script>

<template>
  <div class="page-stack">
    <div class="page-heading">
      <div>
        <h1>Operations overview</h1>
        <p>Element Plus template for Vue admin systems and enterprise workflows.</p>
      </div>
      <el-button type="primary">Create record</el-button>
    </div>

    <el-row :gutter="16">
      <el-col :xs="24" :md="8">
        <el-card>
          <el-statistic title="Active workflows" :value="142" />
        </el-card>
      </el-col>
      <el-col :xs="24" :md="8">
        <el-card>
          <el-statistic title="Pending approvals" :value="38" />
        </el-card>
      </el-col>
      <el-col :xs="24" :md="8">
        <el-card>
          <el-statistic title="Risk alerts" :value="9" />
        </el-card>
      </el-col>
    </el-row>

    <el-row :gutter="16">
      <el-col :xs="24" :lg="16">
        <el-card header="Work queue">
          <el-table :data="workRecords" style="width: 100%">
            <el-table-column prop="title" label="Task" />
            <el-table-column prop="owner" label="Owner" width="140" />
            <el-table-column label="Risk" width="120">
              <template #default="{ row }">
                <el-tag :type="riskType(row)">{{ row.risk }}</el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="status" label="Status" width="120" />
          </el-table>
        </el-card>
      </el-col>
      <el-col :xs="24" :lg="8">
        <el-card header="Quick action">
          <el-form label-position="top">
            <el-form-item label="Record name">
              <el-input placeholder="Enter a task or resource" />
            </el-form-item>
            <el-form-item label="Owner">
              <el-input placeholder="Team or person" />
            </el-form-item>
            <el-button type="primary" class="full-width">Submit</el-button>
          </el-form>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

// src/features/dashboard/DashboardPage.tsx
import { Alert, Button, Card, Col, Form, Input, Row, Space, Statistic, Table, Tag, Typography } from "antd";
import type { ColumnsType } from "antd/es/table";
import { metrics, type WorkItem, workItems } from "./dashboard-model";

const columns: ColumnsType<WorkItem> = [
  { title: "Task", dataIndex: "title", key: "title" },
  { title: "Owner", dataIndex: "owner", key: "owner", width: 140 },
  {
    title: "Priority",
    dataIndex: "priority",
    key: "priority",
    width: 110,
    render: (priority) => <Tag color={priority === "P0" ? "red" : priority === "P1" ? "orange" : "blue"}>{priority}</Tag>,
  },
  {
    title: "Status",
    dataIndex: "status",
    key: "status",
    width: 130,
    render: (status) => <Tag>{status}</Tag>,
  },
];

export function DashboardPage() {
  return (
    <Space direction="vertical" size={20} className="page-stack">
      <div className="page-heading">
        <div>
          <Typography.Title level={2}>Operations overview</Typography.Title>
          <Typography.Text type="secondary">Dense enterprise UI with typed data tables and validated forms.</Typography.Text>
        </div>
        <Button type="primary">Create record</Button>
      </div>

      <Row gutter={[16, 16]}>
        {metrics.map((metric) => (
          <Col key={metric.key} xs={24} md={8}>
            <Card>
              <Statistic title={metric.label} value={metric.value} />
              <Tag color={metric.tone === "good" ? "green" : metric.tone === "warn" ? "gold" : "red"}>
                {metric.trend > 0 ? "+" : ""}
                {metric.trend}% weekly
              </Tag>
            </Card>
          </Col>
        ))}
      </Row>

      <Row gutter={[16, 16]}>
        <Col xs={24} lg={16}>
          <Card title="Priority work queue">
            <Table columns={columns} dataSource={workItems} pagination={false} />
          </Card>
        </Col>
        <Col xs={24} lg={8}>
          <Card title="Quick action">
            <Form layout="vertical">
              <Form.Item label="Record name" required>
                <Input placeholder="Enter a task or resource" />
              </Form.Item>
              <Form.Item label="Owner">
                <Input placeholder="Team or person" />
              </Form.Item>
              <Button type="primary" block>
                Submit
              </Button>
            </Form>
          </Card>
        </Col>
      </Row>

      <Alert type="info" showIcon message="Profile-ready" description="Use profiles/index.json to map product pages, tables, forms, API clients, and route boundaries." />
    </Space>
  );
}
